Delete duplicate example file
The file RemoteDebugger.ino in the RemoteDebug_Debugger example sketch appears to be an outdated duplicate of RemoteDebug_Debugger.ino, which is also in that sketch folder. Attempt to compile the sketch with both these files in place results in several "redefinition" errors:

RemoteDebugger:154:13: error: redefinition of 'RemoteDebug Debug'

 RemoteDebug Debug;

             ^