Update RemoteDebug_Basic.ino
I needed to have a string in Debug.begin() in order for the code to compile in the Arduino IDE in OSX

I get the error:

exit status 1
no matching function for call to 'RemoteDebug::begin()'